actions:
  - name: auto_workbench_craft_chest
    preconditions:
      inventory.category.plank: ">= 8"
      nearby_workbench: true
    effects:
      inventory.category.plank: "-8"
      inventory.chest: "+1"
    cost: 10
    skill: workbench_craft
    params:
      recipe: chest
      count: 1
  - name: auto_workbench_craft_furnace
    preconditions:
      inventory.cobblestone: ">= 8"
      nearby_workbench: true
    effects:
      inventory.cobblestone: "-8"
      inventory.furnace: "+1"
    cost: 10
    skill: workbench_craft
    params:
      recipe: furnace
      count: 1
  - name: auto_workbench_craft_wooden_sword
    preconditions:
      inventory.category.plank: ">= 2"
      inventory.stick: ">= 1"
      nearby_workbench: true
    effects:
      inventory.category.plank: "-2"
      inventory.stick: "-1"
      inventory.wooden_sword: "+1"
    cost: 10
    skill: workbench_craft
    params:
      recipe: wooden_sword
      count: 1
  - name: auto_workbench_craft_wooden_shovel
    preconditions:
      inventory.category.plank: ">= 1"
      inventory.stick: ">= 2"
      nearby_workbench: true
    effects:
      inventory.category.plank: "-1"
      inventory.stick: "-2"
      inventory.wooden_shovel: "+1"
      inventory.category.shovel: true
    cost: 10
    skill: workbench_craft
    params:
      recipe: wooden_shovel
      count: 1
  - name: auto_workbench_craft_wooden_pickaxe
    preconditions:
      inventory.category.plank: ">= 3"
      inventory.stick: ">= 2"
      nearby_workbench: true
    effects:
      inventory.category.plank: "-3"
      inventory.stick: "-2"
      inventory.wooden_pickaxe: "+1"
      inventory.category.pickaxe: true
    cost: 10
    skill: workbench_craft
    params:
      recipe: wooden_pickaxe
      count: 1
  - name: auto_workbench_craft_wooden_axe
    preconditions:
      inventory.category.plank: ">= 3"
      inventory.stick: ">= 2"
      nearby_workbench: true
    effects:
      inventory.category.plank: "-3"
      inventory.stick: "-2"
      inventory.wooden_axe: "+1"
      inventory.category.axe: true
    cost: 10
    skill: workbench_craft
    params:
      recipe: wooden_axe
      count: 1
  - name: auto_workbench_craft_wooden_hoe
    preconditions:
      inventory.category.plank: ">= 2"
      inventory.stick: ">= 2"
      nearby_workbench: true
    effects:
      inventory.category.plank: "-2"
      inventory.stick: "-2"
      inventory.wooden_hoe: "+1"
    cost: 10
    skill: workbench_craft
    params:
      recipe: wooden_hoe
      count: 1
  - name: auto_workbench_craft_stone_sword
    preconditions:
      inventory.cobblestone: ">= 2"
      inventory.stick: ">= 1"
      nearby_workbench: true
    effects:
      inventory.cobblestone: "-2"
      inventory.stick: "-1"
      inventory.stone_sword: "+1"
    cost: 10
    skill: workbench_craft
    params:
      recipe: stone_sword
      count: 1
  - name: auto_workbench_craft_stone_shovel
    preconditions:
      inventory.cobblestone: ">= 1"
      inventory.stick: ">= 2"
      nearby_workbench: true
    effects:
      inventory.cobblestone: "-1"
      inventory.stick: "-2"
      inventory.stone_shovel: "+1"
      inventory.category.shovel: true
    cost: 10
    skill: workbench_craft
    params:
      recipe: stone_shovel
      count: 1
  - name: auto_workbench_craft_stone_pickaxe
    preconditions:
      inventory.cobblestone: ">= 3"
      inventory.stick: ">= 2"
      nearby_workbench: true
    effects:
      inventory.cobblestone: "-3"
      inventory.stick: "-2"
      inventory.stone_pickaxe: "+1"
      inventory.category.pickaxe: true
      inventory.category.stone_or_better_pickaxe: true
    cost: 10
    skill: workbench_craft
    params:
      recipe: stone_pickaxe
      count: 1
  - name: auto_workbench_craft_stone_axe
    preconditions:
      inventory.cobblestone: ">= 3"
      inventory.stick: ">= 2"
      nearby_workbench: true
    effects:
      inventory.cobblestone: "-3"
      inventory.stick: "-2"
      inventory.stone_axe: "+1"
      inventory.category.axe: true
    cost: 10
    skill: workbench_craft
    params:
      recipe: stone_axe
      count: 1
  - name: auto_workbench_craft_stone_hoe
    preconditions:
      inventory.cobblestone: ">= 2"
      inventory.stick: ">= 2"
      nearby_workbench: true
    effects:
      inventory.cobblestone: "-2"
      inventory.stick: "-2"
      inventory.stone_hoe: "+1"
    cost: 10
    skill: workbench_craft
    params:
      recipe: stone_hoe
      count: 1
  - name: auto_workbench_craft_iron_sword
    preconditions:
      inventory.iron_ingot: ">= 2"
      inventory.stick: ">= 1"
      nearby_workbench: true
    effects:
      inventory.iron_ingot: "-2"
      inventory.stick: "-1"
      inventory.iron_sword: "+1"
    cost: 10
    skill: workbench_craft
    params:
      recipe: iron_sword
      count: 1
  - name: auto_workbench_craft_iron_shovel
    preconditions:
      inventory.iron_ingot: ">= 1"
      inventory.stick: ">= 2"
      nearby_workbench: true
    effects:
      inventory.iron_ingot: "-1"
      inventory.stick: "-2"
      inventory.iron_shovel: "+1"
      inventory.category.shovel: true
    cost: 10
    skill: workbench_craft
    params:
      recipe: iron_shovel
      count: 1
  - name: auto_workbench_craft_iron_pickaxe
    preconditions:
      inventory.iron_ingot: ">= 3"
      inventory.stick: ">= 2"
      nearby_workbench: true
    effects:
      inventory.iron_ingot: "-3"
      inventory.stick: "-2"
      inventory.iron_pickaxe: "+1"
      inventory.category.pickaxe: true
      inventory.category.stone_or_better_pickaxe: true
      inventory.category.iron_or_better_pickaxe: true
    cost: 10
    skill: workbench_craft
    params:
      recipe: iron_pickaxe
      count: 1
  - name: auto_workbench_craft_iron_axe
    preconditions:
      inventory.iron_ingot: ">= 3"
      inventory.stick: ">= 2"
      nearby_workbench: true
    effects:
      inventory.iron_ingot: "-3"
      inventory.stick: "-2"
      inventory.iron_axe: "+1"
      inventory.category.axe: true
    cost: 10
    skill: workbench_craft
    params:
      recipe: iron_axe
      count: 1
  - name: auto_workbench_craft_iron_hoe
    preconditions:
      inventory.iron_ingot: ">= 2"
      inventory.stick: ">= 2"
      nearby_workbench: true
    effects:
      inventory.iron_ingot: "-2"
      inventory.stick: "-2"
      inventory.iron_hoe: "+1"
    cost: 10
    skill: workbench_craft
    params:
      recipe: iron_hoe
      count: 1
  - name: auto_workbench_craft_diamond_sword
    preconditions:
      inventory.diamond: ">= 2"
      inventory.stick: ">= 1"
      nearby_workbench: true
    effects:
      inventory.diamond: "-2"
      inventory.stick: "-1"
      inventory.diamond_sword: "+1"
    cost: 10
    skill: workbench_craft
    params:
      recipe: diamond_sword
      count: 1
  - name: auto_workbench_craft_diamond_shovel
    preconditions:
      inventory.diamond: ">= 1"
      inventory.stick: ">= 2"
      nearby_workbench: true
    effects:
      inventory.diamond: "-1"
      inventory.stick: "-2"
      inventory.diamond_shovel: "+1"
      inventory.category.shovel: true
    cost: 10
    skill: workbench_craft
    params:
      recipe: diamond_shovel
      count: 1
  - name: auto_workbench_craft_diamond_pickaxe
    preconditions:
      inventory.diamond: ">= 3"
      inventory.stick: ">= 2"
      nearby_workbench: true
    effects:
      inventory.diamond: "-3"
      inventory.stick: "-2"
      inventory.diamond_pickaxe: "+1"
      inventory.category.pickaxe: true
      inventory.category.stone_or_better_pickaxe: true
      inventory.category.iron_or_better_pickaxe: true
      inventory.category.diamond_or_better_pickaxe: true
    cost: 10
    skill: workbench_craft
    params:
      recipe: diamond_pickaxe
      count: 1
  - name: auto_workbench_craft_diamond_axe
    preconditions:
      inventory.diamond: ">= 3"
      inventory.stick: ">= 2"
      nearby_workbench: true
    effects:
      inventory.diamond: "-3"
      inventory.stick: "-2"
      inventory.diamond_axe: "+1"
      inventory.category.axe: true
    cost: 10
    skill: workbench_craft
    params:
      recipe: diamond_axe
      count: 1
  - name: auto_workbench_craft_diamond_hoe
    preconditions:
      inventory.diamond: ">= 2"
      inventory.stick: ">= 2"
      nearby_workbench: true
    effects:
      inventory.diamond: "-2"
      inventory.stick: "-2"
      inventory.diamond_hoe: "+1"
    cost: 10
    skill: workbench_craft
    params:
      recipe: diamond_hoe
      count: 1
  - name: auto_workbench_craft_iron_helmet
    preconditions:
      inventory.iron_ingot: ">= 5"
      nearby_workbench: true
    effects:
      inventory.iron_ingot: "-5"
      inventory.iron_helmet: "+1"
    cost: 10
    skill: workbench_craft
    params:
      recipe: iron_helmet
      count: 1
  - name: auto_workbench_craft_iron_chestplate
    preconditions:
      inventory.iron_ingot: ">= 8"
      nearby_workbench: true
    effects:
      inventory.iron_ingot: "-8"
      inventory.iron_chestplate: "+1"
    cost: 10
    skill: workbench_craft
    params:
      recipe: iron_chestplate
      count: 1
  - name: auto_workbench_craft_iron_leggings
    preconditions:
      inventory.iron_ingot: ">= 7"
      nearby_workbench: true
    effects:
      inventory.iron_ingot: "-7"
      inventory.iron_leggings: "+1"
    cost: 10
    skill: workbench_craft
    params:
      recipe: iron_leggings
      count: 1
  - name: auto_workbench_craft_iron_boots
    preconditions:
      inventory.iron_ingot: ">= 4"
      nearby_workbench: true
    effects:
      inventory.iron_ingot: "-4"
      inventory.iron_boots: "+1"
    cost: 10
    skill: workbench_craft
    params:
      recipe: iron_boots
      count: 1
  - name: auto_workbench_craft_diamond_helmet
    preconditions:
      inventory.diamond: ">= 5"
      nearby_workbench: true
    effects:
      inventory.diamond: "-5"
      inventory.diamond_helmet: "+1"
    cost: 10
    skill: workbench_craft
    params:
      recipe: diamond_helmet
      count: 1
  - name: auto_workbench_craft_diamond_chestplate
    preconditions:
      inventory.diamond: ">= 8"
      nearby_workbench: true
    effects:
      inventory.diamond: "-8"
      inventory.diamond_chestplate: "+1"
    cost: 10
    skill: workbench_craft
    params:
      recipe: diamond_chestplate
      count: 1
  - name: auto_workbench_craft_diamond_leggings
    preconditions:
      inventory.diamond: ">= 7"
      nearby_workbench: true
    effects:
      inventory.diamond: "-7"
      inventory.diamond_leggings: "+1"
    cost: 10
    skill: workbench_craft
    params:
      recipe: diamond_leggings
      count: 1
  - name: auto_workbench_craft_diamond_boots
    preconditions:
      inventory.diamond: ">= 4"
      nearby_workbench: true
    effects:
      inventory.diamond: "-4"
      inventory.diamond_boots: "+1"
    cost: 10
    skill: workbench_craft
    params:
      recipe: diamond_boots
      count: 1
